# Generated by Django 5.1.7 on 2025-03-31 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, verbose_name='Dia da semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de término')),
                ('vagas_disponiveis', models.PositiveIntegerField(default=0, verbose_name='Vagas disponíveis')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='inscricoes.curso')),
            ],
            options={
                'verbose_name': 'Horário do Curso',
                'verbose_name_plural': 'Horários dos Cursos',
                'unique_together': {('curso', 'dia_semana', 'horario_inicio', 'horario_fim')},
            },
        ),
    ]
