# Generated by Django 5.1.6 on 2025-03-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_inscricao_data_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cursos',
            field=models.ManyToManyField(related_name='inscricoes', to='inscricoes.curso'),
        ),
    ]
