# Generated by Django 5.1.7 on 2025-03-31 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_horariocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to='inscricoes.horariocurso'),
        ),
    ]
