# Generated by Django 5.1.7 on 2025-04-01 00:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_inscricao_horario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curso',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscricoes.funcionario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='horarios_disponiveis',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='inscricoes.horariocurso'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='horarios_selecionados',
            field=models.ManyToManyField(related_name='inscricoes', to='inscricoes.horariocurso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='limite_inscricoes',
            field=models.IntegerField(blank=True, help_text='Número máximo de inscrições permitidas', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cursos',
            field=models.ManyToManyField(related_name='funcionarios', to='inscricoes.curso'),
        ),
        migrations.AlterField(
            model_name='horariocurso',
            name='vagas_disponiveis',
            field=models.IntegerField(help_text='Número de vagas disponíveis neste horário', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='horario',
        ),
    ]
