# Generated by Django 5.1.6 on 2025-03-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_alter_curso_options_curso_limite_inscricoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
    ]
