# Generated by Django 5.1.7 on 2025-04-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_alter_inscricao_unique_together_curso_funcionario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='horarios_selecionados',
        ),
        migrations.CreateModel(
            name='CursoInscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='inscricoes.curso')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.horariocurso')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_inscritos', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Curso Inscrito',
                'verbose_name_plural': 'Cursos Inscritos',
                'unique_together': {('inscricao', 'curso')},
            },
        ),
    ]
