# Generated by Django 5.1.7 on 2025-04-05 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_remove_inscricao_cursos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariocurso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='horariocurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horarios_disponiveis',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='limite_inscricoes',
        ),
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='vagas_total',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='curso',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='telefone_whatsapp',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dia_semana', models.CharField(max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('vagas', models.IntegerField(default=30)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='inscricoes.curso')),
            ],
            options={
                'unique_together': {('curso', 'dia_semana', 'horario_inicio', 'horario_fim')},
            },
        ),
        migrations.CreateModel(
            name='InscricaoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.turma')),
            ],
            options={
                'unique_together': {('inscricao', 'turma')},
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='turmas',
            field=models.ManyToManyField(through='inscricoes.InscricaoTurma', to='inscricoes.turma'),
        ),
        migrations.DeleteModel(
            name='CursoInscrito',
        ),
        migrations.DeleteModel(
            name='HorarioCurso',
        ),
    ]
