# Generated by Django 4.2.10 on 2026-07-16 23:31

import datetime
import django.core.validators
from django.db import migrations, models
import inscricoes.models


def preencher_anos_letivos(apps, schema_editor):
    Inscricao = apps.get_model('inscricoes', 'Inscricao')
    Turma = apps.get_model('inscricoes', 'Turma')
    InscricaoTurma = apps.get_model('inscricoes', 'InscricaoTurma')

    ano_atual = datetime.date.today().year

    for inscricao in Inscricao.objects.all().only('id', 'data_inscricao', 'ano_letivo'):
        ano = inscricao.data_inscricao.year if inscricao.data_inscricao else ano_atual
        if inscricao.ano_letivo != ano:
            inscricao.ano_letivo = ano
            inscricao.save(update_fields=['ano_letivo'])

    ano_por_turma = {}
    for relacao in InscricaoTurma.objects.select_related('inscricao').all().only('turma_id', 'inscricao__ano_letivo'):
        ano_relacao = relacao.inscricao.ano_letivo
        if relacao.turma_id not in ano_por_turma or ano_relacao > ano_por_turma[relacao.turma_id]:
            ano_por_turma[relacao.turma_id] = ano_relacao

    for turma in Turma.objects.all().only('id', 'ano_letivo'):
        ano = ano_por_turma.get(turma.id, ano_atual)
        if turma.ano_letivo != ano:
            turma.ano_letivo = ano
            turma.save(update_fields=['ano_letivo'])


def desfazer_preenchimento_anos_letivos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_turma_vagas_originais'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ano_letivo',
            field=models.IntegerField(db_index=True, default=inscricoes.models.ano_letivo_atual, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.IntegerField(db_index=True, default=inscricoes.models.ano_letivo_atual, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.RunPython(preencher_anos_letivos, desfazer_preenchimento_anos_letivos),
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('curso', 'ano_letivo', 'dia_semana', 'horario_inicio', 'horario_fim')},
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('cpf', 'ano_letivo'), name='uniq_inscricao_cpf_ano_letivo'),
        ),
    ]
