# Generated by Django 4.2.10 on 2026-07-29 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0008_alter_turma_unique_together_inscricao_ano_letivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncontroTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encontros', to='inscricoes.turma')),
            ],
            options={
                'ordering': ['dia_semana', 'horario_inicio'],
                'unique_together': {('turma', 'dia_semana', 'horario_inicio', 'horario_fim')},
            },
        ),
    ]
