# Generated by Django 4.2.10 on 2026-08-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0010_normalizar_turmas_logicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('institucional', 'Institucional'), ('financeiro', 'Financeiro'), ('regularidade', 'Regularidade'), ('administrativo', 'Administrativo')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='documentos_transparencia/', verbose_name='Arquivo')),
                ('ano_referencia', models.IntegerField(blank=True, null=True, verbose_name='Ano de Referência')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem na tela')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['ordem', '-data_publicacao', 'titulo'],
            },
        ),
    ]
