# Generated by Django 4.2.10 on 2026-09-22 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0011_documentotransparencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotransparencia',
            name='arquivo',
            field=models.FileField(upload_to='documentos_transparencia/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Arquivo'),
        ),
    ]
